name: first workflow
on:
 workflow_dispatch:
jobs:
 secondjob:
  runs-on: ubuntu-latest
  steps:
   - name: secondJob script
     shell: bash
     run: |
      echo this is the second job
      echo and this is a multi-line script
