name: All Stale branch Workflow
on:
 workflow_dispatch:
jobs:
  all-scan-br:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: List and tag stale branches
      id: stale-branches
      run: |
        git fetch --prune
        threshold="1 mins"
        for branch in $(git for-each-ref --format '%(refname:short) refs/heads/*'); do
          branch_name=$(echo "$branch" | awk '{print $1}')
          echo "branch_name=$branch_name"
 
          if [[ "$branch_name" != "main" || "$branch_name" != "origin/main/" || $branch_name" != "refs/heads/*" ]]; then
           last_commit_date=$(git log -n 1 --format="%cd" --date=iso "$branch_name")
            if [[ "$(date -d "$last_commit_date" +%s)" -lt "$(date -d "$threshold" +%s)" ]]; then
             echo "Creating issue for stale branch: $branch_name"
             body=" This branch is stale and may no longer be needed, Please review and consider deleting it"
             gh issue create --title "Stale Branch: $branch_name" --body "$body"  --assignee "arshiyakhan" --label "stale"
           fi
         fi
         echo "$branch_name" >> aa.txt
        done

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
