name: All Stale branch Workflow
on:
 workflow_dispatch:
jobs:
  all-scan-br:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: List stale branches
      id: stale-branches
      run: |
        git fetch --prune
        all_branches=''
        for branch in $(git for-each-ref --format '%(refname:short) refs/heads/*'); do
          branch_name=$(echo "$branch" | awk '{print $1}')
          echo "branch_name=$branch_name"
          all_branches="$all_branches $branch_name"
          echo "i=$all_branches"
        done
        echo "aa: $all_branches"
        echo " $all_branches" > aa.txt
    - name: Create issues for stale branches 1
      run: |
       stale_branches=''
       threshold="1 secs"
       while read -r branch; do
        echo "Checking if its main"
        if [ "$branch" != "main" ]; then
         last_commit_date=$(git log -n 1 --format="%cd" --date=iso "refs/heads/$branch")
         if [[ "$(date -d "$last_commit_date" +%s)" -lt "$(date -d "$threshold" +%s)" ]]; then
          stale_branches="$stale_branches $branch"
          echo "Creating issue for stale branch: $branch"
          body=" This branch is stale and may no longer be needed, Please review and consider deleting it"
          gh issue create --title "Stale Branch: $branch" --body "$body"  --assignee "arshiyakhan" --label "bug"
        fi
       done < aa.txt

        
