name: Stale branch Workflow
on:
 workflow_dispatch:
jobs:
  scan-br:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: List stale branches
      id: stale-branches
      run: |
        git fetch --prune
        all_branches=''
        stale_branches=''
        for branch in $(git for-each-ref --format '%(refname:short) %(committerdate:relative)' refs/heads/*); do
          branch_name=$(echo "$branch" | awk '{print $1}')
          last_commit_date=$(echo "$branch"  | awk '{print $2}')
          all_branches = "$all_branches $branch_name"
          echo "i= $all_branches"
        done
        echo "aa: $all_branches"
