name: Stale branch Workflow
on:
 workflow_dispatch:
jobs:
  scan-br:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Create issues for stale branches
      if: steps.stale_branches.outputs.stale_branches != ''
      run: |
       for branch in ${{ steps.stale-branches.outputs.stale_branches }}; do
        echo "Creating issue for stale branch: $branch"
        body=" This branch is stale and may no longer be needed, Please review and consider deleting it"
        gh issue create --title "Stale Branch: $branch" --body "$body"  --assignee arshiyakhan --labels "stale"
       done
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
     
